### ISSUE TITLE
What happens at ambiguous/non-existing DLST hours?

### ISSUE THREAD

**Issue by martin-trummer** [date-fns/tz#25]
e.g. in the timezone Europe/Vienna

1. `31.02.2024 02:14` does not exist, because the clock is advanced from `01:00` to `03:00`
2. `27.10.2024 01:14` is ambiguous, because the clock will be set back by one hour at `02:00`

So what is supposed to happen when we create such a time? i.e. I think it should just use the newest possible data.

However, my test shows that the result seems to depend on the local timezone?
```typescript
  it('should work for the DLST gap', () => {
    const timeZone = 'Europe/Vienna';
    /**
     * actually 31.02.2024 2:14 does not exist in the timezone Europe/Vienna, because the clock is advanced from 1:00 to 3:00
     * For some reason the output of TZDate seems to depend on the system timezone
     * - system timezone is        'UTC'    -> '2024-03-31T00:14:00.000Z' note: 00:14
     * - system timezone is 'Europe/Vienna' -> '2024-03-31T01:14:00.000Z' note: 01:14
     */
    console.log(new Intl.DateTimeFormat().resolvedOptions().timeZone);
    // this test only works when the system timezone i s UTC?
    expect(new TZDate(2024, 3 - 1, 31, 2, 14, timeZone).getTime()).toBe(new Date('2024-03-31T01:14:00.000Z').getTime());
  });
```

Can someone please clarify this. Maybe I just misunderstood something.

**Comment by kossnocorp** [comment]
First of all, `TZDate` works exactly how would JS work in the given timezone:

Node in the Vienna timezone:

![image](https://github.com/user-attachments/assets/6f6c1db6-59c2-4fde-abc9-8fb10aeb1fd4)

TZDate:

![image](https://github.com/user-attachments/assets/5c867796-8c4f-4b3a-bac1-b42db498d7b8)

Now, regarding your questions:

1. `31.02.2024 02:14` equals `31.02.2024 03:14`:

![image](https://github.com/user-attachments/assets/55eeeb8b-959d-49ca-95b6-d33b534df4a9)

2. `27.10.2024 01:14` is unambiguous. You just can't create a date in the second `02:00` without reaching for UTC first:

![image](https://github.com/user-attachments/assets/40141c1f-4bff-4047-93c4-b3d6d331458a)

But if you use UTC (or [`UTCDate`](https://github.com/date-fns/utc)) you can get to it.

They will print the same date:

![image](https://github.com/user-attachments/assets/ba270053-3c26-4ed1-a1ba-9f1ea7b00ae4)

But will have appropriate timestamps:

![image](https://github.com/user-attachments/assets/cd63ece0-f81d-495a-b771-a213ba2ac497)

I wish I could help you more, but it is impossible without knowing the context or what you're trying to achieve.

**Comment by martin-trummer** [comment]
Sorry If my question was not clear enough, I'll try to explain it in more details.

The wall clock time `31.02.2024 2:14` does not exist in the timezone Europe/Vienna, because the clock is advanced from 1:00 to 3:00 on that day.

## Question 1: How does the lib handle the ambiguity?
i.e. `new TZDate(2024, 3 - 1, 31, 2, 14, 'Europe/Vienna')` is asking the library to create that invalid date

Actually there are different ways to handle this:
e.g. TC39 temporal has a `disambiguation` option, so that the users of the library can choose what should happen: get the **earlier** or **later** date or **throw** an error: see https://tc39.es/proposal-temporal/docs/timezone.html#resolving-time-ambiguity-in-temporal
What is date-fns/tz expected to do in that case? 

## Question2: Why does the result of TZDate depend on the local timezone?
i.e. I do not see why the local timezone should matter, when we ask the library to create the date `31.02.2024 2:14` in timezone 'Europe/Vienna'

Example script:
```typescript
import { TZDate } from '@date-fns/tz';

const currenTimezone = new Intl.DateTimeFormat().resolvedOptions().timeZone;
const targetTimeZone = 'Europe/Vienna';
const dateParts = {
  year: 2024,
  month: 3,
  day: 31,
  hour: 2,
  minute: 14,
};

const date = Temporal.ZonedDateTime.from({
  ...dateParts,
  timeZone: targetTimeZone,
});

const tzDate = new TZDate(dateParts.year, dateParts.month - 1, dateParts.day, dateParts.hour, dateParts.minute, targetTimeZone);

console.log('tz', {
  currenTimezone,
  date,
  tzDate,
  __dateEpochMilliseconds: date.epochMilliseconds,
  tzDateEpochMilliseconds: tzDate.getTime(),
});
```

### local timezone = 'Europe/Vienna' 
```
TZ='Europe/Vienna' deno run --unstable-temporal deno-tz.ts
tz {
  currenTimezone: "Europe/Vienna",
  date: 2024-03-31T03:14:00+02:00[Europe/Vienna],
  tzDate: 2024-03-31T01:14:00.000Z {
    timeZone: "Europe/Vienna",
    internal: 2024-03-31T03:14:00.000Z
  },
  __dateEpochMilliseconds: 1711847640000,
  tzDateEpochMilliseconds: 1711847640000
}
```
Temporal and TZDate return the same date

### local timezone = 'UTC' 
```
deno run --unstable-temporal deno-tz.ts
tz {
  currenTimezone: "UTC",
  date: 2024-03-31T03:14:00+02:00[Europe/Vienna],
  tzDate: 2024-03-31T00:14:00.000Z {
    timeZone: "Europe/Vienna",
    internal: 2024-03-31T01:14:00.000Z
  },
  __dateEpochMilliseconds: 1711847640000,
  tzDateEpochMilliseconds: 1711844040000
}
```
* Temporal is working as expected and returns the same result as before: i.e. the local timezone does not matter
* But TZDate returns a different date now. Why?
