### ISSUE TITLE
Timezone offsets do not work in the TZDate constructor

### ISSUE THREAD

**Issue by sleyland** [date-fns/tz#3]
When looking at the documentation, it mentions that you can provide the timezone in a variety of formats, most notable being that you can provide various _offset_ values in a variety of formats. When using `v1.0.2` and the examples listed in the `README.md` (see [here](https://github.com/date-fns/tz?tab=readme-ov-file#accepted-time-zone-formats)), they produce `Invalid Date` errors instead of actual dates, meaning that the resulting code throws an error when attempting to utilise it for further calculations.

e.g. `new TZDate(2022, 2, 13, "+08:00");` results in `TZDate Invalid Date { timeZone: '+08:00', internal: Invalid Date }` being output when utilising a `console.log` statement.

**What should happen**
The time zone offset should be understood as per the example documentation and a _valid_ TZDate object output.

**Steps to reproduce**

- Install `@date-fns/tz`
- See that `console.log(new Date(2022, 2, 13, "+08:00");` produces an error.

**Comment by kossnocorp** [comment]
Thank you for reporting it. I somehow missed it. I'll make sure to fix it in the next version.

**Comment by kossnocorp** [comment]
It turned out that the Node.js below v22 has no support for `±HH:MM/±HHMM/±HH`. I added a RegExp fallback to support it: https://github.com/date-fns/tz/commit/695bbc971e9b1290d9e58678d209611381d72d8a

I will ship it soon with v1.1.0
