### ISSUE TITLE
Inconsistencies from date-fns-tz

### ISSUE THREAD

**Issue by enchorb** [date-fns/tz#6]
Not sure if I'm just using this new library wrong, or this is a bug?

I have sunrise and sunset times. In the past I was using `toZonedTime(sunrise, timezone)` to get the times in the users timezone which worked great. Now doing `new TZDateMini(sunrise, timezone)` has the correct `internal` date but when you call `new Date()` on it, it returns the same UTC sunrise/sunset time again.

```
  console.log({
    sunrise,
    sunset,
    zonedSunrise: toZonedTime(sunrise, timezone),
    zonedSunset: toZonedTime(sunset, timezone),
    tzZonedSunrise: new TZDateMini(sunrise, timezone),
    tzZzonedSunset: new TZDateMini(sunset, timezone),
    tzDateZonedSunrise: new Date(new TZDateMini(sunrise, timezone)),
    tzDateZonedSunset: new Date(new TZDateMini(sunset, timezone))
  });


{
  sunrise: 2024-09-18T10:40:16.554Z,
  sunset: 2024-09-18T22:58:41.921Z,
  zonedSunrise: 2024-09-18T06:40:16.554Z,
  zonedSunset: 2024-09-18T18:58:41.921Z,
  tzZonedSunrise: TZDateMini 2024-09-18T10:40:16.554Z {
    timeZone: 'America/New_York',
    internal: 2024-09-18T06:40:16.554Z
  },
  tzZzonedSunset: TZDateMini 2024-09-18T22:58:41.921Z {
    timeZone: 'America/New_York',
    internal: 2024-09-18T18:58:41.921Z
  },
  tzDateZonedSunrise: 2024-09-18T10:40:16.554Z,
  tzDateZonedSunset: 2024-09-18T22:58:41.921Z
}
```

**Comment by kossnocorp** [comment]
Hey! It's not a bug. `TZDate` calculates date values in the give time zone, while `toZonedTime` transposes the date and time values. So you want to use `date-fns` transpose function to achieve that:


```ts
import { transpose } from "./lib"; // date-fns"
import { TZDateMini } from "@date-fns/tz";

const sunrise = "2024-09-18T10:40:16.554Z";
const sunset = "2024-09-18T22:58:41.921Z";
const timezone = "America/New_York";

console.log(
  transpose(new TZDateMini(sunrise, timezone), Date),
  transpose(new TZDateMini(sunset, timezone), Date),
);
//=> 2024-09-18T10:40:16.554Z 2024-09-18T22:58:41.921Z
```

![image](https://github.com/user-attachments/assets/7aa09916-808a-4904-9189-60224430818d)

See related issue where I explain it a bit more: https://github.com/date-fns/date-fns/issues/3892

**Comment by kossnocorp** [comment]
I misunderstood the issue, so I removed my original comment. I'll look deeper into that and get back to you.

**Comment by kossnocorp** [comment]
Hey! It's not a bug. `TZDate` calculates date values in the give time zone, while `toZonedTime` transposes the date and time values. So you want to use `date-fns` transpose function to achieve that:

```ts
import { transpose } from "date-fns";
import { TZDateMini } from "@date-fns/tz";
import { toZonedTime } from "date-fns-tz";

const sunrise = "2024-09-18T10:40:16.554Z";
const sunset = "2024-09-18T22:58:41.921Z";
const timezone = "America/New_York";

console.log(
  "date-fns-tz",
  toZonedTime(sunrise, timezone),
  toZonedTime(sunset, timezone),
);

console.log(
  "@date-fns/tz",
  transpose(new TZDateMini(sunrise, timezone), Date),
  transpose(new TZDateMini(sunset, timezone), Date),
);
```

![image](https://github.com/user-attachments/assets/1a927e65-7676-4695-9fa2-5e14ef79801b)

See related issue where I explain it a bit more: https://github.com/date-fns/date-fns/issues/3892
